### ISSUE TITLE
Plans for release to dashing / ros2?

### ISSUE THREAD

**Issue by SteveMacenski** [ros-visualization/interactive_markers#52]

**Comment by jacobperron** [comment]
`interactive_markers` (and the associated display in RViz) will be released into Eloquent.
Since the RViz changes are API/ABI breaking (and rely on API/ABI breaking changes in `tf2_ros`), it is unlikely that they will be backported to Dashing. We can probably release the `interactive_markers` library into Dashing if you think it's useful without the RViz display.

**Comment by SteveMacenski** [comment]
It would be useful to me without the rviz display, but don't do it only on my account, its a tool I use few and far between

**Comment by jacobperron** [comment]
Nevermind, I looked closer and we depend on an interface change in `tf2` https://github.com/ros2/geometry2/pull/121 that is introduced in Eloquent.

https://github.com/ros-visualization/interactive_markers/blob/1ac8c1cb13219ef9d6ff50cd973001675386cb96/include/interactive_markers/message_context.hpp#L60

I think the effort to backport to Dashing is only worth it if there is a strong demand for it.

**Comment by SteveMacenski** [comment]
Fair enough. Can we leave the ticket open though until its been released into some ROS2 distro?

**Comment by jacobperron** [comment]
I've released it and it has been added to the Eloquent distro: https://github.com/ros/rosdistro/pull/22409

Binaries should be available as soon as we do an initial Eloquent release.

**Comment by SteveMacenski** [comment]
Oh great!
